#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

URGENT_VALUE=10

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
  echo " ${BATTERY_POWER}%+"
  echo " ${BATTERY_POWER}%+"
  echo "#ffff66"
elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
  echo " ${BATTERY_POWER}%-"
  echo " ${BATTERY_POWER}%-"
  echo "#ff7700"
else
  echo " ${BATTERY_POWER}%"
  echo " ${BATTERY_POWER}%"
  echo "#00ff00"
fi

if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
