#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

# Detect running OS
unameOut="$(uname -s)"

cd "$(dirname $0)"/..

# Only run if on Darwin OS
if [ "${unameOut}" = "Darwin" ]; then
    # Run Homebrew through the Brewfile
    echo "› brew bundle"
    brew bundle
elif [ "${unameOut}" = "Linux" ]; then
    sudo apt-get install apt-clone
    sudo apt-clone restore packages-list.apt-clone.tar.gz
fi

# Install pip3 packages
pip3 install -r pip3-packages.txt

# Connect camera to Brave
sudo snap connect brave:camera :camera

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
