#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

# Detect running OS
unameOut="$(uname -s)"

cd "$(dirname $0)"/..

# Only run if on Darwin OS
if [ "${unameOut}" = "Darwin" ]; then
    # Run Homebrew through the Brewfile
    echo "› brew bundle"
    brew bundle
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
