#!/bin/bash

echo 'Applying macOS system defaults...'
defaults write NSGlobalDomain _HIHideMenuBar "true"
defaults write NSGlobalDomain AppleKeyboardUIMode "3"
defaults write NSGlobalDomain ApplePressAndHoldEnabled "false"
defaults write NSGlobalDomain InitialKeyRepeat "10"
defaults write NSGlobalDomain KeyRepeat "1"
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled "false"
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled "false"
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled "false"
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled "false"
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled "false"
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode "true"
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 "true"
defaults write dock autohide "true"
defaults write dock mru-spaces "false"
defaults write dock orientation "bottom"
defaults write dock showhidden "true"
defaults write finder AppleShowAllExtensions "true"
defaults write finder FXEnableExtensionChangeWarning "false"
defaults write finder QuitMenuItem "true"
defaults write trackpad Clicking "true"
defaults write trackpad TrackpadThreeFingerDrag "true"
